//////////////////////////////
// Load full IS13 ComParE LLD
//////////////////////////////

include /Users/ayaanb/Downloads/opensmile-3.0.2-macos-armv8/config/is09-13/IS13_ComParE.conf


////////////////////////////////////////
// CSV sink for the final LLD features
////////////////////////////////////////

[componentInstances:cComponentManager]
instance[myCsvSink].type = cCsvSink

[myCsvSink:cCsvSink]
reader.dmInstance = dataMemory
reader.dmLevel = is13_lld_nzsmo
filename = os_features.csv
append = 0
printHeader = 1
frameIndex = 0
frameTime = 0
